server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: postgres
    platform: postgres
    driver-class-name: org.postgresql.Driver
    data: classpath:/data.sql
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true